name: test and packer build
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/webapp-CI-2.yml
    secrets: inherit

  build:
    needs: test
    name: Packer Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      GCP_ZONE: ${{ vars.GCP_ZONE }}
      SOURCE_IMAGE_FAMILY: ${{ vars.SOURCE_IMAGE_FAMILY }}
      SSH_USERNAME: ${{ vars.SSH_USERNAME }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      DISK_SIZE: ${{ vars.DISK_SIZE }}
      DISK_TYPE: ${{ vars.DISK_TYPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pq
        run: sudo apt-get install jq -y

      - name: zip file
        run: zip -r webapp.zip ../webapp

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Packer init
        run: packer init packer/main.pkr.hcl

      - name: Packer build
        run: packer build packer/main.pkr.hcl

      - name: Set image name
        id: get_image_name
        run: echo "AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)" >> $GITHUB_ENV

      - name: Make image template
        env:
          DB_HOST: ${{ vars.TF_DB_HOST }}
          DB_USER: ${{ vars.TF_DB_USER }}
          DB_PASSWORD: ${{ vars.TF_DB_PASSWORD }}
          DB_NAME: ${{ vars.TF_DB_NAME }}
        run: |
          gcloud beta compute instance-templates create webapp-instance-template- --project=csye6225-cloudapp-dev \
          --machine-type=n2-standard-2 --network-interface=network-tier=STANDARD,subnet=webapp \
          --instance-template-region=projects/csye6225-cloudapp-dev/regions/us-east1 \
          --metadata=startup-script=\#\!/bin/bash$'\n'$'\n'if\ \[\ -f\ /opt/webapp/.env\ \]\;\ then$'\n'\ \ echo\ \"File\ .env\ already\ exists.\"$'\n'\ \ exit\ 0$'\n'fi$'\n'echo\ \"Creating\ .env\ file...\"$'\n'sudo\ tee\ -a\ /opt/webapp/.env\ \>\ /dev/null\ \<\<\ EOF$'\n'PORT=\$PORT$'\n'DB_HOST=\$DB_HOST$'\n'DB_USER=\$DB_USER$'\n'DB_PASSWORD=\$DB_PASSWORD$'\n'DB_NAME=\$DB_NAME$'\n'EOF$'\n'chown\ csye6225:csye6225\ /opt/webapp/.env$'\n' \
          --maintenance-policy=MIGRATE --provisioning-model=STANDARD \
          --service-account=webapp-service-account@csye6225-cloudapp-dev.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write \
          --region=us-east1 --tags=webapp-http,db-allow \
          --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=projects/csye6225-cloudapp-dev/global/images/$AMI_ID,kms-key=projects/csye6225-cloudapp-dev/locations/us/keyRings/Key-ring/cryptoKeys/vm-crypto-key,mode=rw,size=20,type=pd-standard \
          --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
  