name: test and packer build
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  test:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/webapp-CI-2.yml
    secrets: inherit

  build:
    needs: test
    name: Packer Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: zip file
        run: zip -r webapp.zip webapp

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v2

      - name: Check gcloud installation
        run: gcloud info

      - name: Packer init
        run: packer init packer/main.pkr.hcl

      - name: Packer build
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ vars.DB_USER }}
          DB_NAME: ${{ vars.DB_NAME }}
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCP_ZONE: ${{ vars.GCP_ZONE }}
        run: packer build packer/main.pkr.hcl
