name: webapp CI 2
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    name: user test
    runs-on: ubuntu-latest
    env:
      DB_USER: test
      DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      DB_NAME: test
    steps:
      - name: setup Database
        run: |
          # start the postgres
          sudo systemctl start postgresql

          # create user and database
          sudo -u postgres psql -U postgres -c "create user $DB_USER with password '$DB_PASSWORD'"
          sudo -u postgres psql -U postgres -c "create database $DB_NAME with owner $DB_USER"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test --ci
