name: webapp CI 2
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: user test
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_USER: test
    #       POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #       POSTGRES_DB: test
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - name: setup Database
        env:
          DB_USER: test
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: test
        run: |
          # init db
          sudo postgresql-setup --initdb 

          # change the longin method in pg_hba.conf
          find / -name "pg_hba.conf" -exec sed -i 's/ident/scram-sha-256/g' {} +;

          # start the postgres
          sudo systemctl start postgresql

          # create user and database
          sudo -u postgres psql -U postgres -c "create user ${DB_USER} with password '${DB_PASSWORD}'"
          sudo -u postgres psql -U postgres -c "create database ${DB_NAME} with owner ${DB_USER}"
          sudo -u postgres psql -U postgres -c "grant all privileges on database ${DB_NAME} to ${DB_USER}"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test
        env:
          DB_USER: test
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: test
        run: yarn test --ci
