name: webapp CI
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  setup-enviornment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
